export const products = [
  {
    id: 1,
    title: "Open Your Mind",
    price: 5000,
    stock: 2,
    description: "Necesitas algo a tu altura!",
    category: "remeras",
    img: "https://res.cloudinary.com/dwtd9n613/image/upload/v1682380067/f87gm5nw06cjse70myjj.jpg",
  },
  {
    id: 2,
    title: "Run advance",
    price: 19500,
    stock: 5,
    description: "Ultra livianas y con un look impecable",
    category: "zapatillas",
    img: "https://res.cloudinary.com/dwtd9n613/image/upload/v1682365972/cld-sample-5.jpg",
  },
  {
    id: 3,
    title: "I Wanna Be",
    price: 9000,
    stock: 5,
    description: "I wanna Be your doctor",
    category: "remeras",
    img: "https://res.cloudinary.com/dwtd9n613/image/upload/v1682380067/mjwkpnylss92ogxwtpah.jpg",
  },
  {
    id: 4,
    title: "Chroma jees",
    price: 7800,
    stock: 5,
    description: "Mockup kit",
    category: "remeras",
    img: "https://res.cloudinary.com/dwtd9n613/image/upload/v1682380067/f6iit5z3qasulmzhgxil.jpg",
  },
  {
    id: 5,
    title: "Eastwood INC",
    price: 4800,
    stock: 5,
    description: "Eastwood lookeate",
    category: "remeras",
    img: "https://res.cloudinary.com/dwtd9n613/image/upload/v1682380067/lxc9x1jvxnvgfwsrak70.jpg",
  },
  {
    id: 6,
    title: "Last ShoINC",
    price: 17800,
    stock: 5,
    description: "Last ShoINC",
    category: "zapatillas",
    img: "https://res.cloudinary.com/dwtd9n613/image/upload/v1682380067/e0as5bcbmtlxxocsgtop.jpg",
  },
  {
    id: 7,
    title: "Black model",
    price: 17800,
    stock: 5,
    description: "Zapatillas clasicc",
    category: "zapatillas",
    img: "https://res.cloudinary.com/dwtd9n613/image/upload/v1682380070/hxqfls1affgjfgi5ckvn.jpg",
  },
  {
    id: 8,
    title: "Tri Blend Crew",
    price: 7811,
    stock: 5,
    description: "Tri Blend Crew",
    category: "remeras",
    img: "https://res.cloudinary.com/dwtd9n613/image/upload/v1682380070/agz7szqqqlbkq9w3u3te.jpg",
  },
  {
    id: 9,
    title: "Short Sleeve",
    price: 6812,
    stock: 5,
    description: "Short Sleeve",
    category: "remeras",
    img: "https://res.cloudinary.com/dwtd9n613/image/upload/v1682380070/ulisb9wqmmjl8prkpqpz.jpg",
  },
  {
    id: 10,
    title: "Orange slow",
    price: 17813,
    stock: 5,
    description: "Orange slow",
    category: "pantalones",
    img: "https://res.cloudinary.com/dwtd9n613/image/upload/v1682380070/syspcxjtabgl0tmd79qi.jpg",
  },
  {
    id: 11,
    title: "Pantalon Clasico",
    price: 10814,
    stock: 5,
    description: "Classic ",
    category: "pantalones",
    img: "https://res.cloudinary.com/dwtd9n613/image/upload/v1682380070/hkyvrnvd5eqi1e1of8wc.jpg",
  },
  {
    id: 12,
    title: "Sunshine",
    price: 17800,
    stock: 5,
    description: "Sunshine",
    category: "remeras",
    img: "https://res.cloudinary.com/dwtd9n613/image/upload/v1682380071/wghugzqp9gytk77oqt6f.jpg",
  },
  {
    id: 13,
    title: "Remereas clasicas",
    price: 17800,
    stock: 5,
    description: "remeras Clasicas",
    category: "remeras",
    img: "https://res.cloudinary.com/dwtd9n613/image/upload/v1682380071/ortkpjdrqng3azpcjiee.jpg",
  },
];
