export const products = [
  {
    id: 1,
    title: "Nike 360",
    price: 15000,
    stock: 2,
    description: "Estas son las mejores zapatillas",
    category: "pantalones",
    img: "https://res.cloudinary.com/dwtd9n613/image/upload/v1682380067/f87gm5nw06cjse70myjj.jpg",
  },
  {
    id: 2,
    title: "wilson advance",
    price: 14500,
    stock: 5,
    description: "Ultra livianas y cuentan con camara de aire zapa",
    category: "pantalones",
    img: "https://res.cloudinary.com/dwtd9n613/image/upload/v1682365972/cld-sample-5.jpg",
  },
  {
    id: 3,
    title: "Puma",
    price: 19000,
    stock: 5,
    description:
      "Las clasicas zapatillas que van para cualquier momento del dia",
    category: "remeras",
    img: "https://res.cloudinary.com/dwtd9n613/image/upload/v1682380067/mjwkpnylss92ogxwtpah.jpg",
  },
  {
    id: 4,
    title: "Jaguar",
    price: 17800,
    stock: 5,
    description: "Zapatillas de ultima generacion para el deporte",
    category: "remeras",
    img: "https://res.cloudinary.com/dwtd9n613/image/upload/v1682380067/f6iit5z3qasulmzhgxil.jpg",
  },
  {
    id: 5,
    title: "Jaguar",
    price: 17800,
    stock: 5,
    description: "Zapatillas de ultima generacion para el deporte",
    category: "remeras",
    img: "https://res.cloudinary.com/dwtd9n613/image/upload/v1682380067/lxc9x1jvxnvgfwsrak70.jpg",
  },
  {
    id: 6,
    title: "Jaguar",
    price: 17800,
    stock: 5,
    description: "Zapatillas de ultima generacion para el deporte",
    category: "remeras",
    img: "https://res.cloudinary.com/dwtd9n613/image/upload/v1682380067/e0as5bcbmtlxxocsgtop.jpg",
  },
  {
    id: 7,
    title: "Jaguar",
    price: 17800,
    stock: 5,
    description: "Zapatillas de ultima generacion para el deporte",
    category: "remeras",
    img: "https://res.cloudinary.com/dwtd9n613/image/upload/v1682380070/hxqfls1affgjfgi5ckvn.jpg",
  },
  {
    id: 8,
    title: "Jaguar",
    price: 17811,
    stock: 5,
    description: "Zapatillas de ultima generacion para el deporte",
    category: "remeras",
    img: "https://res.cloudinary.com/dwtd9n613/image/upload/v1682380070/agz7szqqqlbkq9w3u3te.jpg",
  },
  {
    id: 9,
    title: "Jaguar",
    price: 17812,
    stock: 5,
    description: "Zapatillas de ultima generacion para el deporte",
    category: "remeras",
    img: "https://res.cloudinary.com/dwtd9n613/image/upload/v1682380070/ulisb9wqmmjl8prkpqpz.jpg",
  },
  {
    id: 10,
    title: "Jaguar",
    price: 17813,
    stock: 5,
    description: "Zapatillas de ultima generacion para el deporte",
    category: "remeras",
    img: "https://res.cloudinary.com/dwtd9n613/image/upload/v1682380070/syspcxjtabgl0tmd79qi.jpg",
  },
  {
    id: 11,
    title: "Jaguar",
    price: 17814,
    stock: 5,
    description: "Zapatillas de ultima generacion para el deporte",
    category: "remeras",
    img: "https://res.cloudinary.com/dwtd9n613/image/upload/v1682380070/hkyvrnvd5eqi1e1of8wc.jpg",
  },
  {
    id: 12,
    title: "Jaguar",
    price: 17800,
    stock: 5,
    description: "Zapatillas de ultima generacion para el deporte",
    category: "remeras",
    img: "https://res.cloudinary.com/dwtd9n613/image/upload/v1682380071/wghugzqp9gytk77oqt6f.jpg",
  },
  {
    id: 13,
    title: "Jaguar",
    price: 17800,
    stock: 5,
    description: "Zapatillas de ultima generacion para el deporte",
    category: "remeras",
    img: "https://res.cloudinary.com/dwtd9n613/image/upload/v1682380071/ortkpjdrqng3azpcjiee.jpg",
  },
];
